# **Mini-Projeto Avaliativo - Módulo 1 - Semana 07**

## Introdução
 Análise Exploratória de Dados (AED) aplicada a uma base de varejo com 830 mil registros e 14 colunas. Representa as compras efetuadas desde o ano 2019 até o ano 2022 contendo informações das mesmas, além disso possui dados dos produtos e clientes


## Significado das colunas
1. DATA: Data da compra
2. CO_ID: Compra ID
3. CL_ID: Cliente ID
4. CL_GENERO: Cliente Genero
5. CL_EC: Cliente Estado Civil
6. CL_FHL: Cliente Qde Filhos
7. CL_SEG: Cliente Segmento
8. PR_ID: Produto ID
9. PR_CAT: Produto Categoria
10. PR_NOME: Produto Nome


## Requisitos
1. Sprint 1 (Leitura e diagnóstico)
2. Sprint 2 (Limpeza e padronização)
3. Sprint 3 (Funções e organização)
4. Sprint 4 (Análise)
5. Sprint 5 (Exportação e comunicação)
6. Sprint 6 (Revisão e entrega)



## Fluxo de trabalho integrando com o Github
1. Processo de subida para o Git: feature/xxx > develop > main
2. Cada feature/xxx vai representar um Sprint (feature/sprint1,feature/sprint2 etc)
3. No final de cada sprint vai ser feito um merge de cada branch feature/xxx na develop
4. No final do projeto vai ser feito um merge da develop na main


---


* Autor: Maximiliano Markowsky
* [Repositorio Miniprojeto_MaximilianoMarkowsky_T8](https://github.com/mmarkowsky/Miniprojeto_MaximilianoMarkowsky_T8)

# Sprint 1 (Leitura e diagnóstico)
* Criação da branch feature/sprint1 a partir da develop
* Obter o CSV
* Importar com panda
* Inspecionar a estrutura
* Registrar valores ausentes, duplicatas e inconsistências de formato de dados, inconsitencia de texto e dados fora do dominio.

Upload do Arquivo .csv na pasta do repositorio

In [1]:
from google.colab import files
uploaded = files.upload()

print(list(uploaded.keys()))

Saving base_varejo.csv to base_varejo.csv
['base_varejo.csv']

* Criação do dataframe utilizando a biblioteca "Pandas" para manipulação e análise de dados

In [2]:
import pandas as pd

df_varejo = pd.read_csv("base_varejo.csv",sep=';')

* Criação de uma copia do DF para começar o tratamento dos dados sem modificar o arquivo original

In [3]:
df_varejo_limpo = df_varejo.copy()

* Criação da seguinte função "diagnosticar_dataframe", a mesma vai gerar um relatório completo do diagnóstico e estrutura do DataFrame.A função vai receber como parâmetro um DF e tem como intuito analisar os seguintes pontos:

1.   Quantidade de filas e colunas utilizando a função shape()
2.   Quantidade de registros duplicados utilizando a função duplicated()
3.   Quantidade de registros nulos, null ,com espaços ou apenas aspas utilizando a função isnull() e expressões regulares
4.   Exibição transposta dos primeiros 5 registros do DF utilizando a função head()
5.   Exibição das quantidades de registros tipos de dados , valores nulos por coluna utilizando a função info()
6.   Exibição dos nomes das colunas utilizando columns.to_list()
7.   Contagem de valores negativos para colunas IDs
8.   Verificar valores unicos na coluna CL_GENERO

In [4]:
def diagnosticar_dataframe(df):
    """
    Gera um relatório completo de diagnóstico e estrutura de um DataFrame.
    """
    print("="*60)
    print("📋 RELATÓRIO DE DIAGNÓSTICO DO DATAFRAME")
    print("="*60)

    # 1. Estrutura (Linhas e Colunas)
    linhas, colunas = df.shape
    print(f"\n 📊 Dimensões: {linhas} linhas e {colunas} colunas.")
    print("\n" + "-"*60 + "\n")

    # 2. Contagem de registros duplicados
    total_duplicados = df.duplicated().sum()
    porcentagem_duplicados = ((total_duplicados * 100) / len(df)).round(2)
    print(f"👥 Registros duplicados: {total_duplicados}.")
    print(f"👥 Porcentagem de registros duplicados: {porcentagem_duplicados}%.")
    print("\n" + "-"*60 + "\n")

    # 3. Análise detalhada por coluna (Nulos e Espaços vazios)
    nulos_reais = df.isnull().sum()
    porcentagem_nulos_reais = ((nulos_reais * 100) / len(df)).round(2)
    valores_invalidos = ['', ' ', '#N/D','NULL','N/D','undefined']
    colunas_valores_invalidos = df_varejo.isin(valores_invalidos).sum()
    porcentagem_valores_invalidos= ((colunas_valores_invalidos * 100) / len(df)).round(2)

    # Criar um DataFrame descritivo das colunas
    df_analise_cols = pd.DataFrame({
        'Valores Nulos (NaN)': nulos_reais,
        'Porcentagem Valores Nulos (NaN)':porcentagem_nulos_reais,
        'Contagem valores invalidos': colunas_valores_invalidos,
        'Porcentagem valores invalidos':porcentagem_valores_invalidos
    })

    print("🔍 Registros Nulos , Valores invalidos:")
    display(df_analise_cols)
    print("\n" + "-"*60 + "\n")

    # 4. Exibição das primeiras 5 filas do data frame
    print("🔄 Visualização transposta das primeiras 5 filas do dataframe:\n")
    df_transposto = df.head(5).reset_index().T
    display(df_transposto)
    print("\n" + "-"*60 + "\n")

    # 5. Estrutura do data frame com informações de Quantidade de registros por coluna ,Tipo de dado da coluna ,Valores nulos por coluna:
    print("🔬 Visualização do data frame com informações por coluna e tipo:\n")
    df_transposto = df.info()
    display(df_transposto)
    print("\n" + "-"*60 + "\n")

    # 6. Nomes das colunas
    print("🚀 Visualização dos nomes das colunas:\n")
    display(df_varejo.columns.to_list())
    print("\n" + "-"*60 + "\n")

    # 7. Contagem de valores negativos para colunas IDs
    print("🧮 Quantidade de valores negativos nas colunas dos IDs:\n")
    df_numerico = df_varejo.select_dtypes(include=['number'])
    mascara_negativos = df_numerico < 0
    display(mascara_negativos.sum())
    print("\n" + "-"*60 + "\n")

    # 8. Verificar valores unicos na coluna CL_GENERO
    print("📄 Visualização dos valores unicos da coluna CL_GENERO:\n")
    valores = df_varejo['CL_GENERO'].unique()
    print(f"Coluna CL_GENERO': {valores}")
    print("\n" + "="*60 + "\n")

* A função diagnosticar_dataframe é chamada enviando o DF df_varejo

In [5]:
diagnosticar_dataframe(df_varejo_limpo)

============================================================
📋 RELATÓRIO DE DIAGNÓSTICO DO DATAFRAME
============================================================

 📊 Dimensões: 830000 linhas e 14 colunas.

------------------------------------------------------------

👥 Registros duplicados: 96553.
👥 Porcentagem de registros duplicados: 11.63%.

------------------------------------------------------------

🔍 Registros Nulos , Valores invalidos:

,Valores Nulos (NaN),Porcentagem Valores Nulos (NaN),Contagem valores invalidos,Porcentagem valores invalidos
DATA,0,0.0,0,0.00
CO_ID,0,0.0,0,0.00
CL_ID,0,0.0,0,0.00
CL_GENERO,0,0.0,0,0.00
CL_EC,0,0.0,0,0.00
CL_FHL,0,0.0,0,0.00
CL_SEG,0,0.0,0,0.00
PR_ID,0,0.0,0,0.00
PR_CAT,0,0.0,3650,0.44
PR_NOME,0,0.0,3650,0.44
Unnamed: 10,830000,100.0,0,0.00
Unnamed: 11,830000,100.0,0,0.00
Unnamed: 12,830000,100.0,0,0.00
Unnamed: 13,830000,100.0,0,0.00

------------------------------------------------------------

🔄 Visualização transposta das primeiras 5 filas do dataframe:

,0,1,2,3,4
index,0,1,2,3,4
DATA,01/02/2019,01/02/2019,01/02/2019,01/02/2019,01/02/2019
CO_ID,1000,1000,1000,1000,1000
CL_ID,534,534,534,534,534
CL_GENERO,M,M,M,M,M
CL_EC,4,4,4,4,4
CL_FHL,1,1,1,1,1
CL_SEG,C,C,C,C,C
PR_ID,67,70,178,4,175
PR_CAT,BEBIDAS,BEBIDAS,HIGIENE,ALIMENTOS,LIMPEZA
PR_NOME,REFRIGERANTE GUARANA,REFRIGERANTE OUTROS,LENCO UMEDECIDO,ABACAXI,LIMPADOR MULTIUSO
Unnamed: 10,NaN,NaN,NaN,NaN,NaN
Unnamed: 11,NaN,NaN,NaN,NaN,NaN
Unnamed: 12,NaN,NaN,NaN,NaN,NaN
Unnamed: 13,NaN,NaN,NaN,NaN,NaN

------------------------------------------------------------

🔬 Visualização do data frame com informações por coluna e tipo:

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 830000 entries, 0 to 829999
Data columns (total 14 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   DATA         830000 non-null  object
 1   CO_ID        830000 non-null  int64
 2   CL_ID        830000 non-null  int64
 3   CL_GENERO    830000 non-null  object
 4   CL_EC        830000 non-null  int64
 5   CL_FHL       830000 non-null  int64
 6   CL_SEG       830000 non-null  object
 7   PR_ID        830000 non-null  int64
 8   PR_CAT       830000 non-null  object
 9   PR_NOME      830000 non-null  object
 10  Unnamed: 10  0 non-null       float64
 11  Unnamed: 11  0 non-null       float64
 12  Unnamed: 12  0 non-null       float64
 13  Unnamed: 13  0 non-null       float64
dtypes: float64(4), int64(5), object(5)
memory usage: 88.7+ MB

None

------------------------------------------------------------

🚀 Visualização dos nomes das colunas:

['DATA',
 'CO_ID',
 'CL_ID',
 'CL_GENERO',
 'CL_EC',
 'CL_FHL',
 'CL_SEG',
 'PR_ID',
 'PR_CAT',
 'PR_NOME',
 'Unnamed: 10',
 'Unnamed: 11',
 'Unnamed: 12',
 'Unnamed: 13']

------------------------------------------------------------

🧮 Quantidade de valores negativos nas colunas dos IDs:

CO_ID          0
CL_ID          0
CL_EC          0
CL_FHL         0
PR_ID          0
Unnamed: 10    0
Unnamed: 11    0
Unnamed: 12    0
Unnamed: 13    0
dtype: int64

------------------------------------------------------------

📄 Visualização dos valores unicos da coluna CL_GENERO:

Coluna CL_GENERO': ['M' 'F']

============================================================

* Exportar arquivo base_varejo_limpo.csv

In [7]:
from google.colab import files

df_varejo_limpo.to_csv('base_varejo_limpo_sprint1.csv', index=False, sep=';', encoding='utf-8-sig')
files.download('base_varejo_limpo_sprint1.csv')

* ***Conclusão diagnostico:*** A analise do DF resultou com uma porcentagem de registros duplicados de quase 12%, valores nulos se apresentam em 4 colunas com 100% de nulos e 2 colunas possuim 3650 nulos.
Conseguimos observar tambem que o tipo do campo "Data" é igual a Object.

# Sprint 2 (Limpeza e padronização)
* Tratar os problemas encontrados.
* Padronizar texto e justificar as escolhas.
* Comparar o diagnóstico antes e depois.
* Exclusão de registros duplicados
* Exclusão de registros nulos
* Formatar campos (Data)

* Criação de uma copia do DF para começar o tratamento dos dados sem modificar o arquivo original

In [8]:
df_varejo_limpo = df_varejo.copy()

* Deletando as colunas com mais do 80% de regsitros nulos. Colunas:
'Unnamed: 10'
'Unnamed: 11'
'Unnamed: 12'
'Unnamed: 13'

In [9]:
# Deletando colunas com mais do 80% de valores nulos
df_varejo_limpo = df_varejo_limpo.drop(columns=['Unnamed: 10','Unnamed: 11','Unnamed: 12','Unnamed: 13'])

print(f"Visualização do DataFrame depois da limpeza:\n")
display(df_varejo_limpo.head(5))

Visualização do DataFrame depois da limpeza:

,DATA,CO_ID,CL_ID,CL_GENERO,CL_EC,CL_FHL,CL_SEG,PR_ID,PR_CAT,PR_NOME
0,01/02/2019,1000,534,M,4,1,C,67,BEBIDAS,REFRIGERANTE GUARANA
1,01/02/2019,1000,534,M,4,1,C,70,BEBIDAS,REFRIGERANTE OUTROS
2,01/02/2019,1000,534,M,4,1,C,178,HIGIENE,LENCO UMEDECIDO
3,01/02/2019,1000,534,M,4,1,C,4,ALIMENTOS,ABACAXI
4,01/02/2019,1000,534,M,4,1,C,175,LIMPEZA,LIMPADOR MULTIUSO

* Deletando as filas com os nomes das colunas "PR_CAT" e "PR_NOME".A quais tinham 3650 registros nulos.

In [10]:
import numpy as np

df_varejo_limpo = df_varejo_limpo.replace(['#N/D'], np.nan)
df_varejo_limpo.dropna(subset=['PR_CAT', 'PR_NOME'], inplace=True)

print(f"Tamanho do DataFrame original: {len(df_varejo)}")
print(f"Tamanho do DataFrame depois da limpeza: {len(df_varejo_limpo)}")
deletados = len(df_varejo) - len(df_varejo_limpo)
print(f"Quantidade de registros deletados: {deletados}")

Tamanho do DataFrame original: 830000
Tamanho do DataFrame depois da limpeza: 826350
Quantidade de registros deletados: 3650

* Exclusão dos registros duplicados mantendo no df limpo a primeira aparição

In [11]:
# Deletando registros duplicados mantendo a primeira aparição com o parâmetro (keep='first')
df_varejo_limpo = df_varejo_limpo.drop_duplicates(keep='first')

print(f"Tamanho do DataFrame original: {len(df_varejo)}")
print(f"Tamanho do DataFrame depois da limpeza: {len(df_varejo_limpo)}")
deletados = len(df_varejo) - len(df_varejo_limpo)
print(f"Quantidade de registros deletados: {deletados}")

Tamanho do DataFrame original: 830000
Tamanho do DataFrame depois da limpeza: 730219
Quantidade de registros deletados: 99781

* Reindexar os indices depois da exclusão para que os mesmos sejam consecutivos com a função redex_index()

In [12]:
df_varejo_limpo = df_varejo_limpo.reset_index(drop=True)

* Padronizar os nomes para que não sejam considerados diferentes no momento da analise, foi feita uma função para limpar e normalizar strings (minúsculas, sem acentos/especiais),colunas afetadas 'PR_CAT'	e 'PR_NOME'.

In [13]:
import unicodedata

def normalizar_texto(texto):
  # Garante que é string, remove espaços extras e deixa em minúscula
  texto_str = str(texto).strip().lower()

  # Remove acentos
  texto_sem_acentos = ''.join(
      c for c in unicodedata.normalize('NFD', texto_str)
      if unicodedata.category(c) != 'Mn'
  )

  # Mantém apenas letras, números e espaços simples
  texto_limpo = ''.join(c for c in texto_sem_acentos if c.isalnum() or c.isspace())
  return texto_limpo

df_varejo_limpo['PR_CAT'] = df_varejo_limpo['PR_CAT'].apply(normalizar_texto)
df_varejo_limpo['PR_NOME'] = df_varejo_limpo['PR_NOME'].apply(normalizar_texto)
df_varejo_limpo['CL_SEG'] = df_varejo_limpo['CL_SEG'].apply(normalizar_texto)
df_varejo_limpo['CL_GENERO'] = df_varejo_limpo['CL_GENERO'].apply(normalizar_texto)

display(df_varejo_limpo.head(5))

,DATA,CO_ID,CL_ID,CL_GENERO,CL_EC,CL_FHL,CL_SEG,PR_ID,PR_CAT,PR_NOME
0,01/02/2019,1000,534,m,4,1,c,67,bebidas,refrigerante guarana
1,01/02/2019,1000,534,m,4,1,c,70,bebidas,refrigerante outros
2,01/02/2019,1000,534,m,4,1,c,178,higiene,lenco umedecido
3,01/02/2019,1000,534,m,4,1,c,4,alimentos,abacaxi
4,01/02/2019,1000,534,m,4,1,c,175,limpeza,limpador multiuso

* Formatar campo "Data"

In [14]:
df_varejo_limpo['DATA'] = pd.to_datetime(
    df_varejo_limpo['DATA'],
    format='%d/%m/%Y'
)

display(df_varejo_limpo.head(5))
display("\nNovo tipo da coluna:")
display(df_varejo_limpo['DATA'].dtypes)

,DATA,CO_ID,CL_ID,CL_GENERO,CL_EC,CL_FHL,CL_SEG,PR_ID,PR_CAT,PR_NOME
0,2019-02-01,1000,534,m,4,1,c,67,bebidas,refrigerante guarana
1,2019-02-01,1000,534,m,4,1,c,70,bebidas,refrigerante outros
2,2019-02-01,1000,534,m,4,1,c,178,higiene,lenco umedecido
3,2019-02-01,1000,534,m,4,1,c,4,alimentos,abacaxi
4,2019-02-01,1000,534,m,4,1,c,175,limpeza,limpador multiuso

'\nNovo tipo da coluna:'

dtype('<M8[ns]')

* Exportar arquivo base_varejo_limpo.csv

In [17]:
df_varejo_limpo.to_csv('base_varejo_limpo_sprint2.csv', index=False, sep=';', encoding='utf-8-sig')
files.download('base_varejo_limpo_sprint2.csv')

# Sprint 3 (Funções e organização)
* Criar e chamar uma função de tratamento com parâmetros e retorno.
* Criar e chamar uma função de resumo com parâmetros e retorno.
* Manter uma sequência clara entre leitura, limpeza e análise.

* Foram criadas 3 funções:

1. normalizar_texto(): Vai receber um texto e o mesmo vai ser padronizado em minuscula , sem espaços extras e sem caracteres especias retornando um texto limpo
2. tratamento_dados(): Vai excluir de registros nulos e registros duplicados, padronizar dados das colunas de tipo string (utilizando a primeira função normalizar_texto()) e formatar campo data
3. tratamento_resumo(): Vai mostrar um relatorio de forma clara com as modificações e diferenças entre o DF original e DF limpo

In [18]:
import numpy as np
import unicodedata

def normalizar_texto(texto):
  # Garante que é string, remove espaços extras e deixa em minúscula
  texto_str = str(texto).strip().lower()

  # Remove acentos
  texto_sem_acentos = ''.join(
      c for c in unicodedata.normalize('NFD', texto_str)
      if unicodedata.category(c) != 'Mn'
  )

  # Mantém apenas letras, números e espaços simples
  texto_limpo = ''.join(c for c in texto_sem_acentos if c.isalnum() or c.isspace())
  return texto_limpo


def tratamento_dados(df):
  # Deletando colunas com mais do 80% de valores nulos
  df = df.drop(columns=['Unnamed: 10','Unnamed: 11','Unnamed: 12','Unnamed: 13'])

  # Deletando filas das colunas 'PR_CAT','PR_NOME' com valores nulos
  df = df.replace(['#N/D'], np.nan)
  df.dropna(subset=['PR_CAT', 'PR_NOME'],inplace=True)

  # Deletando registros duplicados mantendo a primeira aparição com o parâmetro (keep='first')
  df = df.drop_duplicates(keep='first')

  #Reindexando os indices depois da exclusão dos registros
  df = df.reset_index(drop=True)

  #Modificar o formato da coluna DATA para o tipo DATETIME
  df['DATA'] = pd.to_datetime(
      df['DATA'],
      format='%d/%m/%Y'
  )

  #Filtrando apenas colunas de tipo String e Object
  df_colunas_string = df.select_dtypes(include=['object', 'string'])
  #Percorrer o dataframe naquelas colunas(tipo Object e String) para normalizar o texto")
  for coluna in df_colunas_string.columns:
    df[coluna] = df[coluna].apply(normalizar_texto)

  return df


def tratamento_resumo(df_original, df_copia):
  # 1. Cálculos de métricas
  tamanho_original = len(df_original)
  tamanho_limpo = len(df_copia)
  deletados = tamanho_original - tamanho_limpo

  # Evita divisão por zero caso o DataFrame original esteja vazio
  porcentagem_deletados = (deletados * 100) / tamanho_original

  # 2. Exibição do Relatório Estruturado
  print("=" * 60)
  print("📋 RELATÓRIO DE TRATAMENTO E LIMPEZA DE DADOS".center(60))
  print("=" * 60)

  print(f"🔹 Tamanho do DataFrame original        : {tamanho_original:,} linhas")
  print(f"🔹 Tamanho do DataFrame pós-limpeza     : {tamanho_limpo:,} linhas")
  print(f"❌ Quantidade de registros deletados    : {deletados:,} ({porcentagem_deletados:.2f}%)")

  print("-" * 60)
  print("📌 TIPOS DE COLUNAS ALTERADAS:")
  print(f"   • Tipo atual da coluna 'DATA'        : {df_copia['DATA'].dtypes}")

  print("-" * 60)
  print("📌 COLUNAS NORMALIZADAS:")
  df_colunas_string = df_copia.select_dtypes(include=['object', 'string'])
  for coluna in df_colunas_string.columns:
    print(f"   • Coluna        : {coluna}")

  print("-" * 60)
  print("👀 VISUALIZAÇÃO DOS PRIMEIROS REGISTROS (PÓS-LIMPEZA):\n")
  # 3. Renderização dos dados (Usa o df_copia recebido no argumento)
  display(df_copia.head(5))
  print("=" * 60)

* Criando uma copia do arquivo original

In [19]:
df_varejo_limpo = df_varejo.copy()

* Aplicar o tratamento na copia do arquivo original utilizando a função tratamento_dados()

In [20]:
df_varejo_limpo = tratamento_dados(df_varejo_limpo)

* Visualizar o resumo do tratamento utilizando a função tratamento_resumo()

In [21]:
tratamento_resumo(df_varejo, df_varejo_limpo)

============================================================
        📋 RELATÓRIO DE TRATAMENTO E LIMPEZA DE DADOS
============================================================
🔹 Tamanho do DataFrame original        : 830,000 linhas
🔹 Tamanho do DataFrame pós-limpeza     : 730,219 linhas
❌ Quantidade de registros deletados    : 99,781 (12.02%)
------------------------------------------------------------
📌 TIPOS DE COLUNAS ALTERADAS:
   • Tipo atual da coluna 'DATA'        : datetime64[ns]
------------------------------------------------------------
📌 COLUNAS NORMALIZADAS:
   • Coluna        : CL_GENERO
   • Coluna        : CL_SEG
   • Coluna        : PR_CAT
   • Coluna        : PR_NOME
------------------------------------------------------------
👀 VISUALIZAÇÃO DOS PRIMEIROS REGISTROS (PÓS-LIMPEZA):

,DATA,CO_ID,CL_ID,CL_GENERO,CL_EC,CL_FHL,CL_SEG,PR_ID,PR_CAT,PR_NOME
0,2019-02-01,1000,534,m,4,1,c,67,bebidas,refrigerante guarana
1,2019-02-01,1000,534,m,4,1,c,70,bebidas,refrigerante outros
2,2019-02-01,1000,534,m,4,1,c,178,higiene,lenco umedecido
3,2019-02-01,1000,534,m,4,1,c,4,alimentos,abacaxi
4,2019-02-01,1000,534,m,4,1,c,175,limpeza,limpador multiuso

============================================================

* Exportar arquivo base_varejo_limpo.csv

In [23]:
df_varejo_limpo.to_csv('base_varejo_limpo_sprint3.csv', index=False, sep=';', encoding='utf-8-sig')
files.download('base_varejo_limpo_sprint3.csv')

# Sprint 4 (Análise)
* Aplicar um filtro
* Calcular as quatro estatísticas obrigatórias
* Produzir dois agrupamentos.
*Interpretar os resultados conforme o significado das linhas da base.

* Criação de um filtro por quantidade de compras por cada clientes. Logo vai ser implementada uma regra para definir o tipo de cliente em uma nova coluna:

In [24]:
#Contagem de compras por clientes, salvando em uma variavel compras_x_cliente
compras_x_cliente = df_varejo_limpo['CL_ID'].value_counts()

#Aplicando uma função lambda para definir o tipo de cliente para cada "CL_ID" do meu DF mapeando com a minha variavel compras_x_cliente
df_varejo_limpo['CL_TIPO'] = df_varejo_limpo['CL_ID'].map(compras_x_cliente).apply(lambda x: 'vip' if x >= 1500 else 'recurrente' if 500 < x & x < 1500 else 'eventual')

display(df_varejo_limpo['CL_TIPO'].value_counts())

CL_TIPO
recurrente    682167
eventual       46525
vip             1527
Name: count, dtype: int64

* Calculo da quantidade COMPRAS em relação ao campo DATA

In [25]:
#Criação uma nova coluna apenas com o ano
df_varejo_limpo['ANO'] = df_varejo_limpo['DATA'].dt.year

#Agrupa por Cliente (CO_ID) e Ano
compras_x_ano = df_varejo_limpo.groupby('ANO')['CO_ID'].agg(
    Quantidade_Por_Ano='count',          # Conta quantas compras foram feitas por ano
).reset_index()

display(compras_x_ano)

    ANO  Quantidade_Por_Ano
0  2019              175325
1  2020              191978
2  2021              215850
3  2022              147066

* Criação de um groupby para responder a seguinte questão:

Questão:
Saber quais são as categorias mais vendidas considerando a quantidade de filhos

In [26]:
compras_fhl_cat = df_varejo_limpo.groupby('CL_FHL')['PR_CAT'].value_counts()
compras_fhl_cat.unstack().style.background_gradient(cmap='Blues',axis=None)

* Criação de um groupby para responder a seguinte questão:

Questão: Saber quais são os 5 produtos mais vendidos agrupando por GENERO e ESTADO CIVIL

In [27]:
#Contagem das vendas por NOME PRODUTO agrupando por ESTADO CIVIL E GENERO
top_produtos_ec_genero = (df_varejo_limpo.groupby(['CL_EC', 'CL_GENERO'])['PR_NOME']
                           .value_counts()
                           .reset_index(name='QUANTIDADE'))

#Filtragem dos primeiros 5 produtos mais vendidos para cada Estado Civil e Genero
top_5_completo = top_produtos_ec_genero.groupby(['CL_EC', 'CL_GENERO']).head(5)

#Mostrar resultado
display(top_5_completo.style.background_gradient(cmap='Blues',axis=None))

* Exportar arquivo base_varejo_limpo.csv

In [29]:
df_varejo_limpo.to_csv('base_varejo_limpo_sprint4.csv', index=False, sep=';', encoding='utf-8-sig')
files.download('base_varejo_limpo_sprint4.csv')

# Sprint 5 (Exportação e comunicação)
* Salvar varejo_limpo.csv
* Escrever as conclusões
* Completar o README com origem dos dados, instruções e decisões de qualidade.

* Conclusões extraidas das consultas

1. Podemos observar que o produto mais vendido independentemente do estado civil e genero é o PRESUNTO COZIDO
2. O QUEIJO DE CABRA é um produto que tem excelentes vendas para o público FEMENINO com ESTADO CIVIL 1 e 3
3. A BANANA é um produto que tem excelentes vendas para o público MASCULINO com ESTADO CIVIL 3, 4 e 5
4. Podemos observar que a categoria mais vendida é "Alimentos" independentemente da quantidade de filhos.
5. Outro ponto importante é que existe um grande volume de compras em TODAS categorias para CLIENTES SEM FILHOS em relação a clientes com filhos
6. A Categoria menos vendida é "Acessorios" independentemente da quantidade de filhos.
7. O Ano com mais vendas foi no 2021

* Exportar arquivo base_varejo_limpo.csv

In [31]:
df_varejo_limpo.to_csv('base_varejo_limpo_final.csv', index=False, sep=';', encoding='utf-8-sig')
files.download('base_varejo_limpo_final.csv')